spring.application.name=tradingBot
spring.output.ansi.enabled=ALWAYS

# No web server needed — this is a CLI bot
spring.main.web-application-type=none

# -------------------------
# Chartink Details
# -------------------------
chartink.loginUrl=https://chartink.com/login
chartink.positiveScanUrl=https://chartink.com/screener/copy-buy-open-equals-to-low-4879
chartink.negativeScanUrl=https://chartink.com/screener/copy-sell-open-high-5802
chartink.username=talktosombuddha@gmail.com
chartink.password=Sachin@1

# -------------------------
# Angel One SmartAPI (Trading App)
# -------------------------
smartapi.apiKey=yb3q6yX9
smartapi.clientId=AAAM062371
smartapi.password=5893
smartapi.totpSecret=GLLLSTZNNHP7ZGF23L4URHHBWU

# -------------------------
# Trading Mode
# -------------------------
# Set to true for paper trading (simulated), false for live trading
trading.paperTrade=true

# -------------------------
# SQLite Database
# -------------------------
spring.datasource.url=jdbc:sqlite:tradingbot.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# Disable DevTools restart to prevent loop
spring.devtools.restart.enabled=false